# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

INGREDIENTS = [
  { name: 'butter' },
  { name: 'onion' },
  { name: 'lemon' },
  { name: 'rice' },
  { name: 'sugar' },
  { name: 'cinnamon' },
  { name: 'chicken breast' },
  { name: 'canned tuna' },
  { name: 'shrimp' },
  { name: 'mayonnaise' },
  { name: 'olive oil' },
  { name: 'bouillon' },
  { name: 'tomato sauce' },
  { name: 'green beans' },
  { name: 'white wine' },
  { name: 'chicken broth' },
  { name: 'peanut butter' },
  { name: 'margarine' },
  { name: 'chocolate' },
  { name: 'coffee' },
  { name: 'egg', regex: '(egg[^plant])|(egg\b)' },
  { name: 'garlic' },
  { name: 'apple' },
  { name: 'pasta' },
  { name: 'brown sugar' },
  { name: 'vanilla' },
  { name: 'ground beef' },
  { name: 'salmon' },
  { name: 'crab' },
  { name: 'ketchup' },
  { name: 'vegetable oil' },
  { name: 'ground ginger' },
  { name: 'tomato paste' },
  { name: 'peas' },
  { name: 'beer' },
  { name: 'mushroom soup' },
  { name: 'almond' },
  { name: 'coconut milk' },
  { name: 'apple sauce' },
  { name: 'orange juice' },
  { name: 'milk' },
  { name: 'tomato' },
  { name: 'banana' },
  { name: 'flour' },
  { name: 'honey' },
  { name: 'garlic powder' },
  { name: 'bacon' },
  { name: 'tilapia' },
  { name: 'prawns' },
  { name: 'mustard' },
  { name: 'cooking spray' },
  { name: 'sesame seed' },
  { name: 'salsa' },
  { name: 'black beans' },
  { name: 'red wine' },
  { name: 'beef broth' },
  { name: 'walnut' },
  { name: 'almond milk' },
  { name: 'strawberry jam' },
  { name: 'tea' },
  { name: 'parmesan' },
  { name: 'potato' },
  { name: 'lime' },
  { name: 'bread' },
  { name: 'confectioners sugar' },
  { name: 'paprika' },
  { name: 'sausage' },
  { name: 'fish fillets' },
  { name: 'scallop' },
  { name: 'vinegar' },
  { name: 'canola oil' },
  { name: 'cream of tartar' },
  { name: 'pesto' },
  { name: 'chickpea' },
  { name: 'vodka' },
  { name: 'tomato soup' },
  { name: 'pecan' },
  { name: 'soy milk' },
  { name: 'graham cracker' },
  { name: 'green tea' },
  { name: 'cheddar' },
  { name: 'carrot' },
  { name: 'strawberry' },
  { name: 'baking powder' },
  { name: 'maple syrup' },
  { name: 'oregano' },
  { name: 'beef steak' },
  { name: 'cod' },
  { name: 'clam' },
  { name: 'soy sauce' },
  { name: 'shortening' },
  { name: 'chili sauce' },
  { name: 'alfredo sauce' },
  { name: 'lentil' },
  { name: 'rum' },
  { name: 'vegetable stock' },
  { name: 'peanut' },
  { name: 'rice milk' },
  { name: 'marshmallow' },
  { name: 'apple juice' },
  { name: 'american cheese' },
  { name: 'bell pepper' },
  { name: 'orange' },
  { name: 'baking soda' },
  { name: 'corn syrup' },
  { name: 'chili powder' },
  { name: 'ham' },
  { name: 'canned salmon' },
  { name: 'lobster' },
  { name: 'balsamic vinegar' },
  { name: 'sesame oil' },
  { name: 'soya sauce' },
  { name: 'beef gravy' },
  { name: 'refried beans' },
  { name: 'whiskey' },
  { name: 'chicken soup' },
  { name: 'cashew' },
  { name: 'hemp milk' },
  { name: 'chocolate syrup' },
  { name: 'tomato juice' },
  { name: 'sour cream' },
  { name: 'basil' },
  { name: 'pineapple' },
  { name: 'bread crumbs' },
  { name: 'molasses' },
  { name: 'red pepper flake' },
  { name: 'hot dog' },
  { name: 'anchovy' },
  { name: 'mussel' },
  { name: 'worcestershire' },
  { name: 'coconut oil' },
  { name: 'apple cider' },
  { name: 'curry paste' },
  { name: 'hummus' },
  { name: 'tequila' },
  { name: 'onion soup' },
  { name: 'flax' },
  { name: 'non dairy creamer' },
  { name: 'potato chips' },
  { name: 'coke' },
  { name: 'cream cheese' },
  { name: 'parsley' },
  { name: 'blueberry' },
  { name: 'cornstarch' },
  { name: 'artificial sweetener' },
  { name: 'cumin' },
  { name: 'pork chops' },
  { name: 'smoked salmon' },
  { name: 'oyster' },
  { name: 'hot sauce' },
  { name: 'peanut oil' },
  { name: 'hoisin sauce' },
  { name: 'chicken gravy' },
  { name: 'chili beans' },
  { name: 'sherry' },
  { name: 'vegetable soup' },
  { name: 'pine nut' },
  { name: 'nutella' },
  { name: 'chocolate milk' },
  { name: 'mozzarella' },
  { name: 'broccoli' },
  { name: 'raisin' },
  { name: 'rolled oats' },
  { name: 'agave nectar' },
  { name: 'cayenne' },
  { name: 'chicken thighs' },
  { name: 'sardines' },
  { name: 'squid' },
  { name: 'barbecue sauce' },
  { name: 'sunflower oil' },
  { name: 'liquid smoke' },
  { name: 'cranberry sauce' },
  { name: 'lima beans' },
  { name: 'bourbon' },
  { name: 'celery soup' },
  { name: 'pistachio' },
  { name: 'chocolate morsels' },
  { name: 'pineapple juice' },
  { name: 'yogurt' },
  { name: 'corn' },
  { name: 'coconut' },
  { name: 'noodle' },
  { name: 'italian seasoning' },
  { name: 'ground turkey' },
  { name: 'tuna steak' },
  { name: 'calamari' },
  { name: 'ranch dressing' },
  { name: 'lard' },
  { name: 'rice wine' },
  { name: 'turkey gravy' },
  { name: 'kidney beans' },
  { name: 'cooking wine' },
  { name: 'dashi' },
  { name: 'almond meal' },
  { name: 'bittersweet chocolate' },
  { name: 'lemonade' },
  { name: 'cream' },
  { name: 'spinach' },
  { name: 'grape' },
  { name: 'flour tortillas' },
  { name: 'thyme' },
  { name: 'cooked chicken' },
  { name: 'whitefish' },
  { name: 'crawfish' },
  { name: 'wine vinegar' },
  { name: 'grape seed oil' },
  { name: 'vegetable bouillon' },
  { name: 'mushroom gravy' },
  { name: 'pinto beans' },
  { name: 'whisky' },
  { name: 'lamb stock' },
  { name: 'hazelnut' },
  { name: 'pudding mix' },
  { name: 'cranberry juice' },
  { name: 'evaporated milk' },
  { name: 'mushroom' },
  { name: 'peach' },
  { name: 'pancake mix' },
  { name: 'onion powder' },
  { name: 'turkey' },
  { name: 'halibut' },
  { name: 'octopus' },
  { name: 'apple cider vinegar' },
  { name: 'corn oil' },
  { name: 'poppy seed' },
  { name: 'sausage gravy' },
  { name: 'edamame' },
  { name: 'liqueur' },
  { name: 'pork stock' },
  { name: 'macadamia' },
  { name: 'raspberry jam' },
  { name: 'espresso' },
  { name: 'whipped cream' },
  { name: 'green beans' },
  { name: 'raspberry' },
  { name: 'yeast' },
  { name: 'nutmeg' },
  { name: 'pork' },
  { name: 'trout' },
  { name: 'cockle' },
  { name: 'cider vinegar' },
  { name: 'almond oil' },
  { name: 'balsamic glaze' },
  { name: 'onion gravy' },
  { name: 'split peas' },
  { name: 'brandy' },
  { name: 'veal stock' },
  { name: 'almond paste' },
  { name: 'dark chocolate' },
  { name: 'fruit juice' },
  { name: 'half and half' },
  { name: 'ginger' },
  { name: 'cranberry' },
  { name: 'cracker' },
  { name: 'ground nutmeg' },
  { name: 'pepperoni' },
  { name: 'haddock' },
  { name: 'conch' },
  { name: 'italian dressing' },
  { name: 'avocado oil' },
  { name: 'miso' },
  { name: 'cream gravy' },
  { name: 'snap peas' },
  { name: 'gin' },
  { name: 'chestnut' },
  { name: 'chocolate chips' },
  { name: 'ginger ale' },
  { name: 'feta' },
  { name: 'chili pepper' },
  { name: 'mango' },
  { name: 'quinoa' },
  { name: 'curry powder' },
  { name: 'whole chicken' },
  { name: 'flounder' },
  { name: 'sea urchin' },
  { name: 'rice vinegar' },
  { name: 'safflower oil' },
  { name: 'wasabi' },
  { name: 'pork gravy' },
  { name: 'soybeans' },
  { name: 'kahlua' },
  { name: 'praline' },
  { name: 'jam' },
  { name: 'club soda' },
  { name: 'monterey jack cheese' },
  { name: 'celery' },
  { name: 'pear' },
  { name: 'brown rice' },
  { name: 'bay leaf' },
  { name: 'chicken leg' },
  { name: 'catfish' },
  { name: 'salad dressing' },
  { name: 'walnut oil' },
  { name: 'fish stock' },
  { name: 'tomato gravy' },
  { name: 'cannellini beans' },
  { name: 'irish cream' },
  { name: 'macaroon' },
  { name: 'white chocolate' },
  { name: 'sprite' },
  { name: 'condensed milk' },
  { name: 'rosemary' },
  { name: 'blackberry' },
  { name: 'cornmeal' },
  { name: 'taco seasoning' },
  { name: 'ground pork' },
  { name: 'mahi mahi' },
  { name: 'tabasco' },
  { name: 'hazelnut oil' },
  { name: 'rose water' },
  { name: 'giblet gravy' },
  { name: 'navy beans' },
  { name: 'triple sec' },
  { name: 'brownie mix' },
  { name: 'kool aid' },
  { name: 'cottage cheese' },
  { name: 'salad greens' },
  { name: 'cherry' },
  { name: 'self rising flour' },
  { name: 'sage' },
  { name: 'chorizo' },
  { name: 'mackerel' },
  { name: 'fish sauce' },
  { name: 'palm oil' },
  { name: 'pickling salt' },
  { name: 'french beans' },
  { name: 'champagne' },
  { name: 'chocolate pudding' },
  { name: 'grenadine' },
  { name: 'ice cream' },
  { name: 'red onion' },
  { name: 'date' },
  { name: 'cake mix' },
  { name: 'clove' },
  { name: 'chicken wings' },
  { name: 'sole' },
  { name: 'teriyaki' },
  { name: 'soybean oil' },
  { name: 'champagne vinegar' },
  { name: 'red beans' },
  { name: 'amaretto' },
  { name: 'jello' },
  { name: 'margarita mix' },
  { name: 'swiss cheese' },
  { name: 'cucumber' },
  { name: 'watermelon' },
  { name: 'saltines' },
  { name: 'allspice' },
  { name: 'beef roast' },
  { name: 'sea bass' },
  { name: 'steak sauce' },
  { name: 'mustard oil' },
  { name: 'bbq rub' },
  { name: 'great northern beans' },
  { name: 'cabernet sauvignon' },
  { name: 'caramel' },
  { name: 'cherry juice' },
  { name: 'velveeta' },
  { name: 'sweet potato' },
  { name: 'berries' },
  { name: 'popcorn' },
  { name: 'turmeric' },
  { name: 'polish sausage' },
  { name: 'red snapper' },
  { name: 'tahini' },
  { name: 'pistachio oil' },
  { name: 'jamaican jerk spice' },
  { name: 'fava beans' },
  { name: 'vermouth' },
  { name: 'chocolate powder' },
  { name: 'pepsi' },
  { name: 'frosting' },
  { name: 'pickle' },
  { name: 'kiwi' },
  { name: 'macaroni cheese mix' },
  { name: 'chive' },
  { name: 'salami' },
  { name: 'swordfish' },
  { name: 'enchilada sauce' },
  { name: 'soya oil' },
  { name: 'accent seasoning' },
  { name: 'bitters' },
  { name: 'candy' },
  { name: 'mountain dew' },
  { name: 'buttermilk' },
  { name: 'avocado' },
  { name: 'grapefruit' },
  { name: 'corn tortillas' },
  { name: 'peppercorn' },
  { name: 'pork roast' },
  { name: 'pollock' },
  { name: 'vinaigrette dressing' },
  { name: 'pickling spice' },
  { name: 'maraschino' },
  { name: 'corn chips' },
  { name: 'ricotta' },
  { name: 'zucchini' },
  { name: 'mandarin' },
  { name: 'ramen' },
  { name: 'ground coriander' },
  { name: 'ground chicken' },
  { name: 'herring' },
  { name: 'oyster sauce' },
  { name: 'mustard powder' },
  { name: 'sake' },
  { name: 'cookies' },
  { name: 'goat cheese' },
  { name: 'cilantro' },
  { name: 'craisins' },
  { name: 'cereal' },
  { name: 'cajun seasoning' },
  { name: 'pork ribs' },
  { name: 'perch' },
  { name: 'honey mustard' },
  { name: 'mango powder' },
  { name: 'grand marnier' },
  { name: 'apricot jam' },
  { name: 'provolone' },
  { name: 'frozen vegetables' },
  { name: 'cantaloupe' },
  { name: 'biscuits' },
  { name: 'coriander' },
  { name: 'spam' },
  { name: 'grouper' },
  { name: 'sriracha' },
  { name: 'adobo seasoning' },
  { name: 'masala' },
  { name: 'chocolate bar' },
  { name: 'blue cheese' },
  { name: 'olive' },
  { name: 'plum' },
  { name: 'stuffing mix' },
  { name: 'celery salt' },
  { name: 'venison' },
  { name: 'caviar' },
  { name: 'caesar dressing' },
  { name: 'kasuri methi' },
  { name: 'dessert wine' },
  { name: 'cookie dough' },
  { name: 'powdered milk' },
  { name: 'asparagus' },
  { name: 'apricot' },
  { name: 'couscous' },
  { name: 'vanilla essence' },
  { name: 'pork shoulder' },
  { name: 'monkfish' },
  { name: 'taco sauce' },
  { name: 'caribbean jerk seasoning' },
  { name: 'schnapps' },
  { name: 'oreo' },
  { name: 'colby cheese' },
  { name: 'cabbage' },
  { name: 'clementine' },
  { name: 'pie crust' },
  { name: 'herbs' },
  { name: 'bologna' },
  { name: 'rockfish' },
  { name: 'mirin' },
  { name: 'brine' },
  { name: 'port wine' },
  { name: 'doritos' },
  { name: 'pepper jack' },
  { name: 'cauliflower' },
  { name: 'prunes' },
  { name: 'bisquick' },
  { name: 'steak seasoning' },
  { name: 'bratwurst' },
  { name: 'lemon sole' },
  { name: 'blue cheese dressing' },
  { name: 'matcha powder' },
  { name: 'sparkling wine' },
  { name: 'chocolate cookies' },
  { name: 'italian cheese' },
  { name: 'dill' },
  { name: 'apple butter' },
  { name: 'chips' },
  { name: 'poultry seasoning' },
  { name: 'prosciutto' },
  { name: 'pike' },
  { name: 'sweet and sour sauce' },
  { name: 'cassia' },
  { name: 'cognac' },
  { name: 'butterscotch' },
  { name: 'soft cheese' },
  { name: 'kale' },
  { name: 'pomegranate' },
  { name: 'angel hair' },
  { name: 'chile powder' },
  { name: 'lamb' },
  { name: 'barramundi' },
  { name: 'thousand island' },
  { name: 'chocolate liqueur' },
  { name: 'blackberry preserves' },
  { name: 'gouda' },
  { name: 'mixed vegetable' },
  { name: 'nectarine' },
  { name: 'coconut flake' },
  { name: 'cardamom' },
  { name: 'corned beef' },
  { name: 'eel' },
  { name: 'picante sauce' },
  { name: 'burgundy wine' },
  { name: 'blueberry jam' },
  { name: 'pepperjack cheese' },
  { name: 'pumpkin' },
  { name: 'fig' },
  { name: 'bread flour' },
  { name: 'italian herbs' },
  { name: 'chicken roast' },
  { name: 'bluefish' },
  { name: 'buffalo sauce' },
  { name: 'limoncello' },
  { name: 'peach preserves' },
  { name: 'romano' },
  { name: 'squash' },
  { name: 'tangerine' },
  { name: 'croutons' },
  { name: 'tarragon' },
  { name: 'lamb chops' },
  { name: 'carp' },
  { name: 'french dressing' },
  { name: 'creme de menthe' },
  { name: 'cherry jam' },
  { name: 'brie' },
  { name: 'mint' },
  { name: 'papaya' },
  { name: 'lasagne' },
  { name: 'garam masala' },
  { name: 'pancetta' },
  { name: 'cuttlefish' },
  { name: 'tartar sauce' },
  { name: 'bloody mary' },
  { name: 'fig jam' },
  { name: 'pizza cheese' },
  { name: 'scallion' },
  { name: 'rhubarb' },
  { name: 'pizza dough' },
  { name: 'marjoram' },
  { name: 'ground lamb' },
  { name: 'pompano' },
  { name: 'cocktail sauce' },
  { name: 'raspberry liquor' },
  { name: 'plum jam' },
  { name: 'ghee' },
  { name: 'sun dried tomato' },
  { name: 'sultanas' },
  { name: 'bagel' },
  { name: 'mustard seed' },
  { name: 'beef ribs' },
  { name: 'arctic char' },
  { name: 'marsala' },
  { name: 'curacao' },
  { name: 'cinnamon roll' },
  { name: 'creme fraiche' },
  { name: 'shallot' },
  { name: 'plantain' },
  { name: 'puff pastry' },
  { name: 'celery seed' },
  { name: 'duck' },
  { name: 'john dory' },
  { name: 'adobo sauce' },
  { name: 'frangelico' },
  { name: 'fudge' },
  { name: 'cheese soup' },
  { name: 'eggplant' },
  { name: 'currant' },
  { name: 'hot dog bun' },
  { name: 'chinese five spice' },
  { name: 'pork belly' },
  { name: 'marlin' },
  { name: 'tzatziki sauce' },
  { name: 'shaoxing wine' },
  { name: 'cookie crumb' },
  { name: 'gruyere' },
  { name: 'beet' },
  { name: 'passion fruit' },
  { name: 'barley' },
  { name: 'italian spice' },
  { name: 'beef liver' },
  { name: 'amberjack' },
  { name: 'sesame dressing' },
  { name: 'absinthe' },
  { name: 'grape jelly' },
  { name: 'pecorino cheese' },
  { name: 'butternut squash' },
  { name: 'guava' },
  { name: 'multigrain bread' },
  { name: 'saffron' },
  { name: 'leg of lamb' },
  { name: 'sturgeon' },
  { name: 'ponzu' },
  { name: 'madeira wine' },
  { name: 'chilli jam' },
  { name: 'custard' },
  { name: 'horseradish' },
  { name: 'persimmons' },
  { name: 'potato flakes' },
  { name: 'onion flake' },
  { name: 'canadian bacon' },
  { name: 'duck sauce' },
  { name: 'ouzo' },
  { name: 'lady fingers' },
  { name: 'muenster' },
  { name: 'leek' },
  { name: 'lychee' },
  { name: 'pretzel' },
  { name: 'herbes de provence' },
  { name: 'beef shank' },
  { name: 'pickapeppa sauce' },
  { name: 'anisette' },
  { name: 'black pudding' },
  { name: 'queso fresco cheese' },
  { name: 'caper' },
  { name: 'lingonberry' },
  { name: 'cornbread' },
  { name: 'chipotle' },
  { name: 'veal' },
  { name: 'yuzu juice' },
  { name: 'grappa' },
  { name: 'chocolate wafer' },
  { name: 'hard cheese' },
  { name: 'brussels sprout' },
  { name: 'tangelos' },
  { name: 'english muffin' },
  { name: 'dill seed' },
  { name: 'chicken giblets' },
  { name: 'cream sauce' },
  { name: 'ciclon' },
  { name: 'gummy worms' },
  { name: 'havarti cheese' },
  { name: 'artichoke heart' },
  { name: 'kumquat' },
  { name: 'cornflour' },
  { name: 'fennel seed' },
  { name: 'cornish hen' },
  { name: 'drambuie' },
  { name: 'biscotti biscuit' },
  { name: 'asiago' },
  { name: 'chia seeds' },
  { name: 'boysenberry' },
  { name: 'crescent roll dough' },
  { name: 'caraway' },
  { name: 'lamb shoulder' },
  { name: 'doughnut' },
  { name: 'mascarpone' },
  { name: 'radish' },
  { name: 'star fruit' },
  { name: 'cream of wheat' },
  { name: 'cacao' },
  { name: 'lamb shank' },
  { name: 'amaretti cookies' },
  { name: 'neufchatel' },
  { name: 'sauerkraut' },
  { name: 'quince' },
  { name: 'coconut flour' },
  { name: 'star anise' },
  { name: 'deer' },
  { name: 'apple jelly' },
  { name: 'halloumi' },
  { name: 'artichoke' },
  { name: 'honeydew' },
  { name: 'pita' },
  { name: 'savory' },
  { name: 'ground veal' },
  { name: 'red pepper jelly' },
  { name: 'paneer' },
  { name: 'portobello mushroom' },
  { name: 'crabapples' },
  { name: 'risotto' },
  { name: 'chili paste' },
  { name: 'pastrami' },
  { name: 'orange jelly' },
  { name: 'brick cheese' },
  { name: 'sweet pepper' },
  { name: 'muffin mix' },
  { name: 'tamarind' },
  { name: 'rabbit' },
  { name: 'jalapeno jelly' },
  { name: 'camembert cheese' },
  { name: 'arugula' },
  { name: 'bicarbonate of soda' },
  { name: 'aniseed' },
  { name: 'sliced turkey' },
  { name: 'mint jelly' },
  { name: 'goat milk' },
  { name: 'spaghetti squash' },
  { name: 'ravioli' },
  { name: 'fenugreek' },
  { name: 'pork loin' },
  { name: 'currant jelly' },
  { name: 'garlic herb cheese' },
  { name: 'capsicum' },
  { name: 'wheat' },
  { name: 'lavender' },
  { name: 'elk' },
  { name: 'lemon jelly' },
  { name: 'edam cheese' },
  { name: 'bok choy' },
  { name: 'rice flour' },
  { name: 'old bay seasoning' },
  { name: 'beef suet' },
  { name: 'quince jelly' },
  { name: 'manchego' },
  { name: 'parsnip' },
  { name: 'polenta' },
  { name: 'lemon balm' },
  { name: 'veal cutlet' },
  { name: 'fontina' },
  { name: 'okra' },
  { name: 'baguette' },
  { name: 'lamb loin' },
  { name: 'stilton cheese' },
  { name: 'yam' },
  { name: 'gnocchi' },
  { name: 'marrow bones' },
  { name: 'emmenthaler cheese' },
  { name: 'fennel' },
  { name: 'vermicelli' },
  { name: 'goose' },
  { name: 'red leicester cheese' },
  { name: 'turnip' },
  { name: 'semolina' },
  { name: 'chicken tenders' },
  { name: 'jarlsberg cheese' },
  { name: 'snow peas' },
  { name: 'wheat germ' },
  { name: 'veal chops' },
  { name: 'bocconcini cheese' },
  { name: 'bean sprouts' },
  { name: 'buckwheat' },
  { name: 'quail' },
  { name: 'farmer cheese' },
  { name: 'seaweed' },
  { name: 'croissants' },
  { name: 'oxtail' },
  { name: 'creme de cassis' },
  { name: 'chard' },
  { name: 'bread dough' },
  { name: 'pheasant' },
  { name: 'wensleydale cheese' },
  { name: 'collard' },
  { name: 'filo dough' },
  { name: 'lamb liver' },
  { name: 'longhorn cheese' },
  { name: 'canned tomato' },
  { name: 'yeast flake' },
  { name: 'moose' },
  { name: 'double gloucester cheese' },
  { name: 'pimiento' },
  { name: 'pierogi' },
  { name: 'turkey liver' },
  { name: 'raclette cheese' },
  { name: 'watercress' },
  { name: 'matzo meal' },
  { name: 'pork liver' },
  { name: 'lancashire cheese' },
  { name: 'tomatillo' },
  { name: 'rye' },
  { name: 'veal shank' },
  { name: 'cheshire cheese' },
  { name: 'rocket' },
  { name: 'tapioca flour' },
  { name: 'foie gras' },
  { name: 'mustard greens' },
  { name: 'shortcrust pastry' },
  { name: 'beef sirloin' },
  { name: 'bamboo shoot' },
  { name: 'potato starch' },
  { name: 'liver sausage' },
  { name: 'rutabaga' },
  { name: 'breadsticks' },
  { name: 'sweetbread' },
  { name: 'endive' },
  { name: 'ciabatta' },
  { name: 'wild boar' },
  { name: 'broccoli rabe' },
  { name: 'spelt' },
  { name: 'snail' },
  { name: 'jicama' },
  { name: 'angel food' },
  { name: 'pigeon' },
  { name: 'kohlrabi' },
  { name: 'tapioca starch' },
  { name: 'duck liver' },
  { name: 'hearts of palm' },
  { name: 'starch' },
  { name: 'goose liver' },
  { name: 'butternut' },
  { name: 'whole wheat flour' },
  { name: 'grouse' },
  { name: 'celery root' },
  { name: 'gram flour' },
  { name: 'ostrich' },
  { name: 'daikon' },
  { name: 'sourdough starter' },
  { name: 'soppressata' },
  { name: 'radicchio' },
  { name: 'wafer' },
  { name: 'alligator' },
  { name: 'porcini' },
  { name: 'bran' },
  { name: 'chinese broccoli' },
  { name: 'challah' },
  { name: 'jerusalem artichoke' },
  { name: 'sponge cake' },
  { name: 'cress' },
  { name: 'malt extract' },
  { name: 'water chestnut' },
  { name: 'sorghum flour' },
  { name: 'dulse' },
  { name: 'micro greens' },
  { name: 'burdock' },
  { name: 'chayote' }
]

CURATED_INGREDIENTS = [
  { name: 'cheese' },
  { name: 'parmesan' },
  { name: 'cheddar' },
  { name: 'american cheese' },
  { name: 'cream cheese' },
  { name: 'mozzarella' },
  { name: 'goat cheese' },
  { name: 'gouda' },
  { name: 'pepperjack cheese' },
  { name: 'romano' },
  { name: 'brie' },
  { name: 'pizza cheese' },
  { name: 'swiss cheese' },
  { name: 'gruyere' },
  { name: 'pecorino cheese' },
  { name: 'asiago' },
  { name: 'mascarpone' },
  { name: 'brick cheese' },
  { name: 'camembert cheese' },
  { name: 'edam cheese' },
  { name: 'manchego' },
  { name: 'stilton cheese' },
  { name: 'emmenthaler cheese' },
  { name: 'cottage cheese' },
  { name: 'queso fresco cheese' },
  { name: 'wensleydale cheese' },
  { name: 'longhorn cheese' },
  { name: 'double gloucester cheese' },
  { name: 'raclette cheese' },
  { name: 'lancashire cheese' },
  { name: 'cheshire cheese' },
  { name: 'red leicester cheese' },
  { name: 'jarlsberg cheese' },
  { name: 'bocconcini cheese' },
  { name: 'farmer cheese' },
  { name: 'garlic herb cheese' },
  { name: 'italian cheese' },
  { name: 'soft cheese' },
  { name: 'blue cheese' },
  { name: 'colby cheese' },
  { name: 'pepper jack' },
  { name: 'cheese' },
  { name: 'ricotta' },
  { name: 'feta' },
  { name: 'provolone' },
  { name: 'velveeta' },
  { name: 'teriyaki' },
  { name: 'tomato sauce' },
  { name: 'pesto' },
  { name: 'milk' },
  { name: 'powdered milk' },
  { name: 'condensed milk' },
  { name: 'couscous' },
  { name: 'sour cream' },
  { name: 'baking powder' },
  { name: 'yeast' },
  { name: 'yogurt' },
  { name: 'cream' },
  { name: 'evaporated milk' },
  { name: 'whipped cream' },
  { name: 'half and half cream' },
  { name: 'chips' },
  { name: 'monterey jack cheese' },
  { name: 'fish sauce' },
  { name: 'soy sauce' },
  { name: 'ice cream' },
  { name: 'tahini' },
  { name: 'tabasco' },
  { name: 'frosting' },
  { name: 'buttermilk' },
  { name: 'lard' },
  { name: 'margarine' },
  { name: 'coconut milk' },
  { name: 'almond milk' },
  { name: 'soy milk' },
  { name: 'rice milk' },
  { name: 'hemp milk' },
  { name: 'non dairy creamer' },
  { name: 'deer' },
  { name: 'spam' },
  { name: 'venison' },
  { name: 'elk' },
  { name: 'wild boar' },
  { name: 'rabbit' },
  { name: 'pheasant' },
  { name: 'quail' },
  { name: 'moose' },
  { name: 'oxtail' },
  { name: 'ostrich' },
  { name: 'snail' },
  { name: 'pigeon' },
  { name: 'grouse' },
  { name: 'sriracha' },
  { name: 'chickpea' },
  { name: 'lentil' },
  { name: 'soybeans' },
  { name: 'hummus' },
  { name: 'edamame' },
  { name: 'vegetables' },
  { name: 'onion' },
  { name: 'garlic' },
  { name: 'tomato' },
  { name: 'potato' },
  { name: 'carrot' },
  { name: 'pepper' },
  { name: 'basil' },
  { name: 'parsley' },
  { name: 'broccoli' },
  { name: 'corn' },
  { name: 'spinach' },
  { name: 'lettuce' },
  { name: 'green beans' },
  { name: 'ginger' },
  { name: 'chili pepper' },
  { name: 'celery' },
  { name: 'rosemary' },
  { name: '' },
  { name: 'red onion' },
  { name: 'cucumber' },
  { name: 'sweet potato' },
  { name: 'pickle' },
  { name: 'avocado' },
  { name: 'zucchini' },
  { name: 'frozen vegetables' },
  { name: 'olive' },
  { name: 'asparagus' },
  { name: 'cabbage' },
  { name: 'cauliflower' },
  { name: 'dill' },
  { name: 'kale' },
  { name: 'ramen' },
  { name: 'pumpkin' },
  { name: 'squash' },
  { name: 'mint' },
  { name: 'scallion' },
  { name: 'sun dried tomato' },
  { name: 'shallot' },
  { name: 'eggplant' },
  { name: 'beet' },
  { name: 'butternut squash' },
  { name: 'horseradish' },
  { name: 'leek' },
  { name: 'caper' },
  { name: 'brussels sprout' },
  { name: 'artichoke heart' },
  { name: 'chia seeds' },
  { name: 'radish' },
  { name: 'sauerkraut' },
  { name: 'artichoke' },
  { name: 'sweet pepper' },
  { name: 'arugula' },
  { name: 'spaghetti squash' },
  { name: 'capsicum' },
  { name: 'bok choy' },
  { name: 'parsnip' },
  { name: 'okra' },
  { name: 'yam' },
  { name: 'fennel' },
  { name: 'turnip' },
  { name: 'snow peas' },
  { name: 'bean sprouts' },
  { name: 'seaweed' },
  { name: 'chard' },
  { name: 'collard' },
  { name: 'canned tomato' },
  { name: 'pimiento' },
  { name: 'watercress' },
  { name: 'tomatillo' },
  { name: 'rocket' },
  { name: 'mustard greens' },
  { name: 'bamboo shoot' },
  { name: 'rutabaga' },
  { name: 'endive' },
  { name: 'broccoli rabe' },
  { name: 'jicama' },
  { name: 'kohlrabi' },
  { name: 'hearts of palm' },
  { name: 'butternut' },
  { name: 'celery root' },
  { name: 'daikon' },
  { name: 'radicchio' },
  { name: 'porcini' },
  { name: 'chinese broccoli' },
  { name: 'jerusalem artichoke' },
  { name: 'cress' },
  { name: 'water chestnut' },
  { name: 'dulse' },
  { name: 'micro greens' },
  { name: 'burdock' },
  { name: 'chayote' },
  { name: 'fruits' },
  { name: 'lemon' },
  { name: 'apple' },
  { name: 'banana' },
  { name: 'lime' },
  { name: 'strawberry' },
  { name: 'orange' },
  { name: 'pineapple' },
  { name: 'blueberry' },
  { name: 'raisin' },
  { name: 'coconut' },
  { name: 'grape' },
  { name: 'peach' },
  { name: 'raspberry' },
  { name: 'cranberry' },
  { name: 'mango' },
  { name: 'pear' },
  { name: 'blackberry' },
  { name: 'cherry' },
  { name: 'date' },
  { name: 'watermelon' },
  { name: 'berries' },
  { name: 'kiwi' },
  { name: 'grapefruit' },
  { name: 'mandarin' },
  { name: 'craisins' },
  { name: 'cantaloupe' },
  { name: 'plum' },
  { name: 'apricot' },
  { name: 'clementine' },
  { name: 'prunes' },
  { name: 'apple butter' },
  { name: 'pomegranate' },
  { name: 'nectarine' },
  { name: 'fig' },
  { name: 'tangerine' },
  { name: 'papaya' },
  { name: 'rhubarb' },
  { name: 'sultanas' },
  { name: 'plantain' },
  { name: 'currant' },
  { name: 'passion fruit' },
  { name: 'guava' },
  { name: 'persimmons' },
  { name: 'lychee' },
  { name: 'lingonberry' },
  { name: 'tangelos' },
  { name: 'kumquat' },
  { name: 'boysenberry' },
  { name: 'star fruit' },
  { name: 'quince' },
  { name: 'honeydew' },
  { name: 'crabapples' },
  { name: 'pork' },
  { name: 'pork shoulder' },
  { name: 'bacon' },
  { name: 'pork chops' },
  { name: 'ground pork' },
  { name: 'pork roast' },
  { name: 'pork ribs' },
  { name: 'pancetta' },
  { name: 'pork belly' },
  { name: 'pork loin' },
  { name: 'pork liver' },
  { name: 'lamb' },
  { name: 'lamb chops' },
  { name: 'ground lamb' },
  { name: 'leg of lamb' },
  { name: 'lamb shoulder' },
  { name: 'lamb shank' },
  { name: 'lamb loin' },
  { name: 'lamb liver' },
  { name: 'beef' },
  { name: 'ground beef' },
  { name: 'beef roast' },
  { name: 'corned beef' },
  { name: 'beef ribs' },
  { name: 'beef liver' },
  { name: 'beef shank' },
  { name: 'beef suet' },
  { name: 'beef sirloin' },
  { name: 'duck' },
  { name: 'duck liver' },
  { name: 'ham' },
  { name: 'pastrami' },
  { name: 'prosciutto' },
  { name: 'bologna' },
  { name: 'salami' },
  { name: 'soppressata' },
  { name: 'herbs' },
  { name: 'cilantro' },
  { name: 'veal' },
  { name: 'ground veal' },
  { name: 'veal cutlet' },
  { name: 'veal chops' },
  { name: 'veal shank' },
  { name: 'goose' },
  { name: 'goose liver' },
  { name: 'turkey' },
  { name: 'ground turkey' },
  { name: 'nuts' },
  { name: 'peanut butter' },
  { name: 'almonds' },
  { name: 'walnut' },
  { name: 'pecan' },
  { name: 'peanut' },
  { name: 'cashew' },
  { name: 'flax' },
  { name: 'pine nut' },
  { name: 'pistachio' },
  { name: 'almond meal' },
  { name: 'hazelnut' },
  { name: 'macadamia' },
  { name: 'almond paste' },
  { name: 'chestnuts' },
  { name: 'praline' },
  { name: 'macaroon' },
  { name: 'peanuts' },
  { name: 'oil' },
  { name: 'olive oil' },
  { name: 'vegetable oil' },
  { name: 'cooking spray' },
  { name: 'canola oil' },
  { name: 'sesame oil' },
  { name: 'coconut oil' },
  { name: 'peanut oil' },
  { name: 'sunflower oil' },
  { name: 'grape seed oil' },
  { name: 'corn oil' },
  { name: 'almond oil' },
  { name: 'avocado oil' },
  { name: 'safflower oil' },
  { name: 'walnut oil' },
  { name: 'hazelnut oil' },
  { name: 'palm oil' },
  { name: 'soybean oil' },
  { name: 'mustard oil' },
  { name: 'pistachio oil' },
  { name: 'soya oil' },
  { name: 'Beans' },
  { name: 'black beans' },
  { name: 'refried beans' },
  { name: 'chili beans' },
  { name: 'lima beans' },
  { name: 'kidney beans' },
  { name: 'pinto beans' },
  { name: 'navy beans' },
  { name: 'french beans' },
  { name: 'red beans' },
  { name: 'fava beans' },
  { name: 'great northern beans' },
  { name: 'cannellini beans' },
  { name: 'liver' },
  { name: 'turkey liver' },
  { name: 'liver sausage' },
  { name: 'foie gras' },
  { name: 'broth/soup/stock' },
  { name: 'stock' },
  { name: 'lamb stock' },
  { name: 'pork stock' },
  { name: 'veal stock' },
  { name: 'vegetable stock' },
  { name: 'chicken broth' },
  { name: 'mushroom soup' },
  { name: 'beef broth' },
  { name: 'tomato soup' },
  { name: 'soup' },
  { name: 'chicken soup' },
  { name: 'onion soup' },
  { name: 'vegetable soup' },
  { name: 'celery soup' },
  { name: 'vegetable bouillon' },
  { name: 'broth' },
  { name: 'pasta' },
  { name: 'spaghetti' },
  { name: 'linguine' },
  { name: 'fusilli' },
  { name: 'vermicelli' },
  { name: 'capellini' },
  { name: 'spaghettini' },
  { name: 'bucatini' },
  { name: 'Tagliatelle' },
  { name: 'pappardelle' },
  { name: 'fettuccine' },
  { name: 'lasagne' },
  { name: 'angel hair' },
  { name: 'ravioli' },
  { name: 'gnocchi' },
  { name: 'bread' },
  { name: 'bread crumbs' },
  { name: 'pretzel' },
  { name: 'cornbread' },
  { name: 'croutons' },
  { name: 'baguette' },
  { name: 'flour' },
  { name: 'pizza dough' },
  { name: 'flour tortillas' },
  { name: 'self rising flour' },
  { name: 'bread flour' },
  { name: 'puff pastry' },
  { name: 'seafood' },
  { name: 'shrimp' },
  { name: 'crab' },
  { name: 'prawns' },
  { name: 'scallop' },
  { name: 'clam' },
  { name: 'lobster' },
  { name: 'mussel' },
  { name: 'oyster' },
  { name: 'squid' },
  { name: 'calamari' },
  { name: 'crawfish' },
  { name: 'octopus' },
  { name: 'cockle' },
  { name: 'conch' },
  { name: 'sea urchin' },
  { name: 'Vinegar' },
  { name: 'wine vinegar' },
  { name: 'apple cider vinegar' },
  { name: 'cider vinegar' },
  { name: 'rice vinegar' },
  { name: 'champagne vinegar' },
  { name: 'Salad dressing' },
  { name: 'italian dressing' },
  { name: 'vinaigrette dressing' },
  { name: 'ranch dressing' },
  { name: 'blue cheese dressing' },
  { name: 'french dressing' },
  { name: 'sesame dressing' },
  { name: 'caesar dressing' },
  { name: 'cocktail sauce' },
  { name: 'fish' },
  { name: 'salmon' },
  { name: 'tilapia' },
  { name: 'fish fillets' },
  { name: 'cod' },
  { name: 'anchovy' },
  { name: 'smoked salmon' },
  { name: 'sardines' },
  { name: 'tuna' },
  { name: 'whitefish' },
  { name: 'halibut' },
  { name: 'trout' },
  { name: 'haddock' },
  { name: 'flounder' },
  { name: 'catfish' },
  { name: 'mahi mahi' },
  { name: 'mackerel' },
  { name: 'sole' },
  { name: 'sea bass' },
  { name: 'red snapper' },
  { name: 'swordfish' },
  { name: 'pollock' },
  { name: 'herring' },
  { name: 'perch' },
  { name: 'grouper' },
  { name: 'caviar' },
  { name: 'monkfish' },
  { name: 'rockfish' },
  { name: 'lemon sole' },
  { name: 'pike' },
  { name: 'barramundi' },
  { name: 'eel' },
  { name: 'bluefish' },
  { name: 'carp' },
  { name: 'cuttlefish' },
  { name: 'pompano' },
  { name: 'arctic char' },
  { name: 'john dory' },
  { name: 'marlin' },
  { name: 'amberjack' },
  { name: 'sturgeon' },
  { name: 'sausage' },
  { name: 'polish sausage' },
  { name: 'bratwurst' },
  { name: 'hot dog' },
  { name: 'pepperoni' },
  { name: 'chorizo' },
  { name: 'salad' },
  { name: 'mushroom' },
  { name: 'portobello mushroom' },
  { name: 'butter' },
  { name: 'ghee' },
  { name: 'chicken' },
  { name: 'chicken roast' },
  { name: 'chicken breast' },
  { name: 'chicken thighs' },
  { name: 'cooked chicken' },
  { name: 'chicken wings' },
  { name: 'ground chicken' },
  { name: 'chicken giblets' },
  { name: 'chicken tenders' },
  { name: 'rice' },
  { name: 'brown rice' },
  { name: 'basmati rice' },
  { name: 'jasmin rice' },
  { name: 'parboiled rice' },
  { name: 'egg', regex: '(egg[^plant])|(egg\b)'  },
  { name: 'chicken egg' },
  { name: 'quail egg' },
  { name: 'ostrich egg' },
  { name: 'peas' },
  { name: 'split peas' },
  { name: 'snap peas' },
  { name: 'gravy' },
  { name: 'turkey gravy' },
  { name: 'mushroom gravy' },
  { name: 'sausage gravy' },
  { name: 'onion gravy' },
  { name: 'cream gravy' },
  { name: 'pork gravy' },
  { name: 'tomato gravy' },
  { name: 'giblet gravy' },
  { name: 'beef gravy' },
  { name: 'wine' },
  { name: 'white wine' },
  { name: 'red wine' },
  { name: 'cooking wine' },
  { name: 'dessert wine' },
  { name: 'port wine' },
  { name: 'sparkling wine' },
  { name: 'cabernet sauvignon' },
  { name: 'shaoxing wine' },
  { name: 'rice wine' },
  { name: 'noodle' },
  { name: 'udon noodle' },
  { name: 'shirataki noodle' },
  { name: 'alcohol' },
  { name: 'beer' },
  { name: 'schnapps' },
  { name: 'vodka' },
  { name: 'rum' },
  { name: 'whiskey' },
  { name: 'tequila' },
  { name: 'sherry' },
  { name: 'bourbon' },
  { name: 'vermouth' },
  { name: 'whisky' },
  { name: 'liqueur' },
  { name: 'brandy' },
  { name: 'gin' },
  { name: 'kahlua' },
  { name: 'irish cream' },
  { name: 'triple sec' },
  { name: 'champagne' },
  { name: 'amaretto' },
  { name: 'ciclon' },
  { name: 'drambuie' },
  { name: 'bitters' },
  { name: 'maraschino' },
  { name: 'sake' },
  { name: 'grand marnier' },
  { name: 'absinthe' },
  { name: 'madeira wine' },
  { name: 'ouzo' },
  { name: 'anisette' },
  { name: 'grappa' },
  { name: 'cognac' },
  { name: 'chocolate liqueur' },
  { name: 'burgundy wine' },
  { name: 'limoncello' },
  { name: 'creme de menthe' },
  { name: 'bloody mary' },
  { name: 'raspberry liquor' },
  { name: 'curacao' },
  { name: 'frangelico' },
  { name: 'meat' },
  { name: 'beef steak' },
  { name: 'chicken leg' },
  { name: 'marrow bones' },
  { name: 'sweetbread' },
  { name: 'alligator' }
]

CATEGORIES = {
  'cheese' => [
    'parmesan',
    'cheddar',
    'american cheese',
    'cream cheese',
    'mozzarella',
    'goat cheese',
    'gouda',
    'pepperjack cheese',
    'romano',
    'brie',
    'pizza cheese',
    'swiss cheese',
    'gruyere',
    'pecorino cheese',
    'asiago',
    'mascarpone',
    'brick cheese',
    'camembert cheese',
    'edam cheese',
    'manchego',
    'stilton cheese',
    'emmenthaler cheese',
    'cottage cheese',
    'queso fresco cheese',
    'wensleydale cheese',
    'longhorn cheese',
    'double gloucester cheese',
    'raclette cheese',
    'lancashire cheese',
    'cheshire cheese',
    'red leicester cheese',
    'jarlsberg cheese',
    'bocconcini cheese',
    'farmer cheese',
    'garlic herb cheese',
    'italian cheese',
    'soft cheese',
    'blue cheese',
    'colby cheese',
    'pepper jack',
    'cheese',
    'ricotta',
    'feta',
    'provolone',
    'velveeta'
  ],
  'mushroom' => [
    'portobello mushroom',
    'mushroom soup',
    'mushroom'
  ],
  'vegetables' => [
    'onion',
    'garlic',
    'tomato',
    'potato',
    'carrot',
    'pepper',
    'basil',
    'parsley',
    'broccoli',
    'corn',
    'spinach',
    'lettuce',
    'green beans',
    'ginger',
    'chili pepper',
    'celery',
    'rosemary',
    'red onion',
    'cucumber',
    'sweet potato',
    'pickle',
    'avocado',
    'zucchini',
    'frozen vegetables',
    'olive',
    'asparagus',
    'cabbage',
    'cauliflower',
    'dill',
    'kale',
    'pumpkin',
    'squash',
    'mint',
    'scallion',
    'sun dried tomato',
    'shallot',
    'eggplant',
    'beet',
    'butternut squash',
    'horseradish',
    'leek',
    'caper',
    'brussels sprout',
    'artichoke heart',
    'chia seeds',
    'radish',
    'sauerkraut',
    'artichoke',
    'sweet pepper',
    'arugula',
    'spaghetti squash',
    'capsicum',
    'bok choy',
    'parsnip',
    'okra',
    'yam',
    'fennel',
    'turnip',
    'snow peas',
    'bean sprouts',
    'seaweed',
    'chard',
    'collard',
    'canned tomato',
    'pimiento',
    'watercress',
    'tomatillo',
    'rocket',
    'mustard greens',
    'bamboo shoot',
    'rutabaga',
    'endive',
    'broccoli rabe',
    'jicama',
    'kohlrabi',
    'hearts of palm',
    'butternut',
    'celery root',
    'daikon',
    'radicchio',
    'porcini',
    'chinese broccoli',
    'jerusalem artichoke',
    'cress',
    'water chestnut',
    'dulse',
    'micro greens',
    'burdock',
    'chayote'
  ],
  'salad' => [
    'salad',
    'lettuce',
    'kale'
  ],
  'butter' => [
    'butter',
    'ghee'
  ],
  'cream' => [
    'ricotta',
    'cream'
  ],
  'fruits' => [
    'lemon',
    'apple',
    'banana',
    'lime',
    'strawberry',
    'orange',
    'pineapple',
    'blueberry',
    'raisin',
    'coconut',
    'grape',
    'peach',
    'raspberry',
    'cranberry',
    'mango',
    'pear',
    'blackberry',
    'cherry',
    'date',
    'watermelon',
    'berries',
    'kiwi',
    'grapefruit',
    'mandarin',
    'craisins',
    'cantaloupe',
    'plum',
    'apricot',
    'clementine',
    'prunes',
    'apple butter',
    'pomegranate',
    'nectarine',
    'fig',
    'tangerine',
    'papaya',
    'rhubarb',
    'sultanas',
    'plantain',
    'currant',
    'passion fruit',
    'guava',
    'persimmons',
    'lychee',
    'lingonberry',
    'tangelos',
    'kumquat',
    'boysenberry',
    'star fruit',
    'quince',
    'honeydew',
    'crabapples'
  ],
  'Beans' => [
    'green beans',
    'black beans',
    'beans',
    'refried beans',
    'chili beans',
    'lima beans',
    'kidney beans',
    'pinto beans',
    'navy beans',
    'french beans',
    'red beans',
    'fava beans',
    'great northern beans',
    'cannellini beans'
  ],
  'meat' => [
    'chicken breast',
    'ground beef',
    'bacon',
    'beef steak',
    'ham',
    'pork chops',
    'chicken thighs',
    'ground turkey',
    'cooked chicken',
    'turkey',
    'pork',
    'chicken leg',
    'ground pork',
    'chicken wings',
    'beef roast',
    'pork roast',
    'ground chicken',
    'pork ribs',
    'pork shoulder',
    'lamb',
    'corned beef',
    'chicken roast',
    'lamb chops',
    'pancetta',
    'ground lamb',
    'beef ribs',
    'duck',
    'pork belly',
    'beef liver',
    'leg of lamb',
    'beef shank',
    'veal',
    'chicken giblets',
    'lamb shoulder',
    'lamb shank',
    'deer',
    'ground veal',
    'rabbit',
    'pork loin',
    'elk',
    'beef suet',
    'veal cutlet',
    'lamb loin',
    'marrow bones',
    'goose',
    'chicken tenders',
    'veal chops',
    'quail',
    'oxtail',
    'pheasant',
    'lamb liver',
    'moose',
    'turkey liver',
    'pork liver',
    'veal shank',
    'beef sirloin',
    'sweetbread',
    'wild boar',
    'snail',
    'pigeon',
    'duck liver',
    'goose liver',
    'grouse',
    'ostrich',
    'alligator'
  ],
  'liver' => [
    'liver',
    'turkey liver',
    'lamb liver',
    'pork liver',
    'liver sausage',
    'foie gras',
    'duck liver',
    'goose liver'
  ],
  'chicken' => [
    'chicken roast',
    'chicken breast',
    'chicken',
    'chicken thighs',
    'cooked chicken',
    'chicken thighs',
    'chicken wings',
    'ground chicken',
    'chicken roast',
    'chicken giblets',
    'chicken tenders'
  ],
  'beef' => [
    'ground beef',
    'beef roast',
    'corned beef',
    'beef ribs',
    'beef liver',
    'beef shank',
    'beef suet',
    'beef sirloin'
  ],
  'pork' => [
    'pork shoulder',
    'bacon',
    'pork chops',
    'pork',
    'ground pork',
    'pork roast',
    'pork ribs',
    'pork shoulder',
    'pancetta',
    'pork belly',
    'pork loin',
    'pork liver'
  ],
  'lamb' => [
    'lamb',
    'lamb chops',
    'ground lamb',
    'leg of lamb',
    'lamb shoulder',
    'lamb shank',
    'lamb loin',
    'lamb liver'
  ],
  'sausage' => [
    'polish sausage',
    'bratwurst',
    'hot dog',
    'sausage',
    'pepperoni',
    'chorizo',
    'liver sausage'
  ],
  'goose' => [
    'goose',
    'goose liver'
  ],
  'turkey' => [
    'ground turkey',
    'turkey'
  ],
  'veal' => [
    'veal',
    'ground veal',
    'veal cutlet',
    'veal chops',
    'veal shank'
  ],
  'duck' => [
    'duck',
    'duck liver'
  ],
  'ham' => [
    'ham',
    'pancetta',
    'pastrami',
    'prosciutto',
    'prosciutto',
    'bologna',
    'salami',
    'soppressata'
  ],
  'herbs' => [
    'cilantro'
  ],
  'nuts' => [
    'peanut butter',
    'almonds',
    'walnut',
    'pecan',
    'peanut',
    'cashew',
    'flax',
    'pine nut',
    'pistachio',
    'almond meal',
    'hazelnut',
    'macadamia',
    'almond paste',
    'chestnuts',
    'praline',
    'macaroon',
    'peanuts',
    'nuts'
  ],
  'fish' => [
    'salmon',
    'tilapia',
    'fish fillets',
    'cod',
    'anchovy',
    'smoked salmon',
    'sardines',
    'tuna',
    'whitefish',
    'halibut',
    'trout',
    'haddock',
    'flounder',
    'catfish',
    'mahi mahi',
    'mackerel',
    'sole',
    'sea bass',
    'red snapper',
    'swordfish',
    'pollock',
    'herring',
    'perch',
    'grouper',
    'caviar',
    'monkfish',
    'rockfish',
    'lemon sole',
    'pike',
    'barramundi',
    'eel',
    'bluefish',
    'carp',
    'cuttlefish',
    'pompano',
    'arctic char',
    'john dory',
    'marlin',
    'amberjack',
    'sturgeon'
  ],
  'seafood' => [
    'shrimp',
    'crab',
    'prawns',
    'scallop',
    'clam',
    'lobster',
    'mussel',
    'oyster',
    'squid',
    'calamari',
    'crawfish',
    'octopus',
    'cockle',
    'conch',
    'sea urchin'
  ],
  'Vinegar' => [
    'wine vinegar',
    'apple cider vinegar',
    'cider vinegar',
    'rice vinegar',
    'vinegar',
    'champagne vinegar'
  ],
  'Salad dressing' => [
    'italian dressing',
    'salad dressing',
    'vinaigrette dressing',
    'ranch dressing',
    'blue cheese dressing',
    'french dressing',
    'sesame dressing',
    'caesar dressing',
    'cocktail sauce'
  ],
  'oil' => [
    'olive oil',
    'vegetable oil',
    'cooking spray',
    'canola oil',
    'sesame oil',
    'coconut oil',
    'peanut oil',
    'sunflower oil',
    'grape seed oil',
    'corn oil',
    'almond oil',
    'avocado oil',
    'safflower oil',
    'walnut oil',
    'hazelnut oil',
    'palm oil',
    'soybean oil',
    'mustard oil',
    'pistachio oil',
    'soya oil',
    'oil'
  ],
  'gravy' => [
    'turkey gravy',
    'mushroom gravy',
    'sausage gravy',
    'onion gravy',
    'cream gravy',
    'pork gravy',
    'tomato gravy',
    'giblet gravy',
    'beef gravy'
  ],
  'peas' => [
    'peas',
    'split peas',
    'snap peas'
  ],
  'egg' => [
    'egg',
    'chicken egg',
    'quail egg',
    'ostrich egg'
  ],
  'wine' => [
    'white wine',
    'wine',
    'red wine',
    'cooking wine',
    'dessert wine',
    'port wine',
    'sparkling wine',
    'cabernet sauvignon',
    'shaoxing wine',
    'rice wine'
  ],
  'broth/soup/stock' => [
    'stock',
    'lamb stock',
    'pork stock',
    'veal stock',
    'vegetable stock',
    'chicken broth',
    'mushroom soup',
    'beef broth',
    'tomato soup',
    'soup',
    'chicken soup',
    'onion soup',
    'vegetable soup',
    'celery soup',
    'vegetable bouillon',
    'broth'
  ],
  'rice' => [
    'rice',
    'brown rice',
    'basmati rice',
    'jasmin rice',
    'parboiled rice'
  ],
  'noodle' => [
    'noodle',
    'udon noodle',
    'shirataki noodle',
    'ramen'
  ],
  'pasta' => [
    'spaghetti',
    'pasta',
    'linguine',
    'fusilli',
    'vermicelli',
    'capellini',
    'spaghettini',
    'bucatini',
    'tagliatelle',
    'pappardelle',
    'fettuccine',
    'lasagne',
    'angel hair',
    'ravioli',
    'gnocchi'
  ],
  'alcohol' => [
    'beer',
    'schnapps',
    'vodka',
    'rum',
    'whiskey',
    'tequila',
    'sherry',
    'bourbon',
    'vermouth',
    'whisky',
    'liqueur',
    'brandy',
    'gin',
    'kahlua',
    'irish cream',
    'triple sec',
    'champagne',
    'amaretto',
    'ciclon',
    'drambuie',
    'bitters',
    'maraschino',
    'sake',
    'grand marnier',
    'absinthe',
    'madeira wine',
    'ouzo',
    'anisette',
    'grappa',
    'cognac',
    'chocolate liqueur',
    'burgundy wine',
    'limoncello',
    'creme de menthe',
    'bloody mary',
    'raspberry liquor',
    'curacao',
    'frangelico'
  ],
  'bread' => [
    'bread',
    'bread crumbs',
    'pretzel',
    'cornbread',
    'croutons',
    'baguette'
  ]
}

def destroy_all_data
  Dose.destroy_all
  puts "doses destroyed"
  Recipe.destroy_all
  puts "recipes destroyed"
  Ingredient.destroy_all
  puts "ingredients destroyed"
end

def generate_ingredients
  INGREDIENTS.each do |ingredient| 
    new_ingredient = Ingredient.create_new(ingredient)
    new_ingredient.save!
    puts "#{new_ingredient.name} created!"
  end
end


def generate_fake_recipes
  50.times do
    name = Faker::Food.dish
    description = Faker::Food.description
    rating = rand(1..5)
  
    recipe = Recipe.new(
      name: name,
      description: description,
      rating: rating,
      url_image: "https://ichef.bbci.co.uk/food/ic/food_16x9_448/recipes/babaganoush_78707_16x9.jpg",
      url: "https://www.bbc.co.uk/food/recipes/baba_ganoush_grilled_50988"
      )
      recipe.save!
      
      all_ingredients = Ingredient.all
      rand(2..5).times do
        added_ingredient = all_ingredients.sample
      p Ingredient.all
      p added_ingredient
      p recipe
      dose = Dose.new(ingredient: added_ingredient, recipe: recipe)
        all_ingredients -= [added_ingredient]
      dose.save!
    end
  end
end
# generate_ingredients

destroy_all_data

# generate_fake_recipes

RecipeFile.all.take(500).each { |recipe_file| recipe_file.convert_bbc_recipe_file }


Recipe.all.each do |recipe|
  recipe.scrape_ingredients! 
  puts "#{recipe} contains #{recipe.ingredients.join(" ")}"
end